version: '2'
networks:
  rede-docker:
    external:
      name: rede-docker
services:
 postgres:
  build: ./postgres
  image: crud-livro/banco
  container_name: banco
  ports: 
    - "5433:5432"
  volumes:
    - ./postgres/data:/var/lib/postgresql/data
  networks: 
    - rede-docker
 web:
  build: .
  image: crud-livro/app
  container_name: app
  ports: 
    - "8082:8080" 
  links: 
    - "postgres:host-banco"
  networks:
    - rede-docker
